import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { installedHost, textReply, toolReply, until } from './fixtures/installed-host.mjs';

test('packed Cursor checkpoints open native review and current preview without cross-session actions', { timeout: 150000 }, async t => {
  const f = await installedHost(t); await f.install(); await f.boot();
  await writeFile(join(f.workspace, 'review-a.txt'), 'Before review\n');
  const workspace = await f.rpc('workspace/create', { path: f.workspace });
  const create = agentPreset => f.rpc('session/create', { workspaceId: workspace.workspace.workspaceId, agentPreset });
  const cursor = await create('omaa-cursor'), codex = await create('omaa-codex');
  let step = 0;
  f.replyWith(payload => !payload.tools?.length ? textReply('Title') : step++ === 0
    ? toolReply('read', { file_path: 'review-a.txt' }) : step === 2
      ? toolReply('write', { file_path: 'review-a.txt', content: 'After review\nSecond line\n' }) : step === 3
      ? toolReply('write', { file_path: 'review-b.txt', content: 'New review file\n' }) : textReply('Two file edits completed.'));
  await f.prompt(cursor.sessionId, 'Edit two files for native review'); f.replyWith();
  assert.equal(await readFile(join(f.workspace, 'review-a.txt'), 'utf8'), 'After review\nSecond line\n');
  await f.prompt(codex.sessionId, 'Separate unchanged session');
  await f.rpc('session/rename', { sessionId: cursor.sessionId, title: 'Cursor review navigation' });
  await f.rpc('session/rename', { sessionId: codex.sessionId, title: 'Codex unchanged session' });
  const browser = await chromium.launch({ headless: true, args: ['--use-mock-keychain', '--password-store=basic'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
  await context.addCookies(f.cookie.split('; ').map(value => { const at = value.indexOf('='); return { name: value.slice(0, at), value: value.slice(at + 1), url: f.origin }; }));
  const page = await context.newPage(), errors = []; page.setDefaultTimeout(15000);
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('.cache', { recursive: true });
  t.after(async () => { try { if (!t.passed && !page.isClosed()) { await page.screenshot({ path: '.cache/checkpoint-browser-failure.png' }); t.diagnostic((await page.locator('body').innerText()).slice(-6000)); t.diagnostic(JSON.stringify(errors)); } } finally { await browser.close(); } });
  await page.goto(f.origin); await page.getByRole('button', { name: /^(Continue|继续)$/ }).click();
  const openSettings = async () => { await page.getByRole('button', { name: 'Cursor 预设设置', exact: true }).click(); await page.getByRole('region', { name: 'Cursor 文件检查点' }).waitFor(); };
  await page.getByText('Cursor review navigation', { exact: true }).first().click(); await openSettings();
  const files = page.getByRole('region', { name: 'Cursor 文件检查点' });
  await files.getByRole('button', { name: '审阅本回合 2 个文件', exact: true }).click();
  const review = page.locator('[data-changes-review]:visible');
  await review.locator('[data-diff-line]').first().waitFor();
  assert.equal(await review.locator('[data-review-tool="split"]').getAttribute('aria-pressed'), 'true');
  await review.locator('[data-review-tool="split"]').click();
  assert.equal(await review.locator('[data-review-tool="split"]').getAttribute('aria-pressed'), 'false');
  await review.locator('[data-review-tool="wrap"]').click();
  assert.equal(await review.locator('[data-review-tool="wrap"]').getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: '.cache/cursor-native-review.png' });
  await openSettings();
  await files.getByText('选择比较文件', { exact: true }).click();
  await files.getByRole('button', { name: 'review-b.txt', exact: true }).click();
  await review.locator('[data-review-file="review-b.txt"]').waitFor();
  await review.locator('[data-review-tool="open-file"]').click();
  await page.locator('[data-textpreview-body]:visible').getByText('New review file', { exact: true }).waitFor();
  await openSettings();
  const a = files.locator('.omaa-checkpoint-file').filter({ hasText: 'review-a.txt' });
  await a.getByRole('button', { name: '预览当前文件', exact: true }).click();
  await page.locator('[data-textpreview-body]:visible').getByText('After review', { exact: true }).waitFor();
  await page.screenshot({ path: '.cache/cursor-current-preview.png' });
  await openSettings();
  await files.getByRole('button', { name: '审阅本回合 2 个文件', exact: true }).waitFor();
  const release = f.holdNextReply(); await f.send(cursor.sessionId, 'Hold current run');
  await until(async () => (await f.api(cursor.sessionId)).value.running);
  await page.waitForFunction(() => {
    const buttons = [...document.querySelectorAll('.omaa-checkpoints button')];
    const writes = buttons.filter(button => /恢复|查找/.test(button.textContent));
    return writes.length > 0 && writes.every(button => button.disabled)
      && buttons.some(button => button.textContent === '预览当前文件' && !button.disabled);
  });
  await page.screenshot({ path: '.cache/cursor-checkpoint-running.png' });
  await page.getByText('Codex unchanged session', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Codex 预设设置', exact: true }).click();
  assert.equal(await page.getByRole('region', { name: 'Cursor 文件检查点' }).count(), 0);
  release(); await until(async () => !(await f.api(cursor.sessionId)).value.running);
  assert.equal(await readFile(join(f.workspace, 'review-a.txt'), 'utf8'), 'After review\nSecond line\n');
  await page.getByText('Cursor review navigation', { exact: true }).first().click(); await openSettings();
  await a.getByRole('button', { name: '恢复文件', exact: true }).click();
  await files.getByRole('status').filter({ hasText: '已恢复 1 个文件' }).waitFor();
  await a.getByRole('button', { name: '预览当前文件', exact: true }).click();
  await page.locator('[data-textpreview-body]:visible').getByText('Before review', { exact: true }).waitFor();
  assert.equal(await readFile(join(f.workspace, 'review-a.txt'), 'utf8'), 'Before review\n');
  await openSettings();
  await files.getByRole('button', { name: '审阅本回合 2 个文件', exact: true }).click();
  await review.getByText('After review', { exact: true }).first().waitFor();
  await page.screenshot({ path: '.cache/cursor-restored-review.png' });
  assert.deepEqual(errors, []);
});
