import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { installedHost, textReply, until } from './fixtures/installed-host.mjs';
const execute = promisify(execFile);

test('packed Codex collects two file comments and clears drafts only after one native batch admission', { timeout: 120000 }, async t => {
  const f = await installedHost(t); await f.install(); await f.boot();
  const git = (...args) => execute('git', args, { cwd: f.workspace, encoding: 'utf8' });
  await git('init'); await git('config', 'user.email', 'fixture@example.invalid'); await git('config', 'user.name', 'OMAA fixture');
  for (const file of ['alpha.txt', 'beta.txt']) await writeFile(join(f.workspace, file), 'First line\nOriginal line\n');
  await git('add', 'alpha.txt', 'beta.txt'); await git('commit', '-m', 'Feedback baseline');
  await writeFile(join(f.workspace, 'alpha.txt'), 'First line\nChanged alpha\n');
  await writeFile(join(f.workspace, 'beta.txt'), 'First line\nChanged beta\n');
  const workspace = await f.rpc('workspace/create', { path: f.workspace });
  const created = await f.rpc('session/create', { workspaceId: workspace.workspace.workspaceId, agentPreset: 'omaa-codex' });
  f.replyWith(payload => textReply(payload.tools?.length ? 'Native feedback acknowledged.' : 'Feedback title'));
  await f.prompt(created.sessionId, 'Review these two file changes');
  await f.rpc('session/rename', { sessionId: created.sessionId, title: 'Codex batch feedback' });
  const browser = await chromium.launch({ headless: true, args: ['--use-mock-keychain', '--password-store=basic'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies(f.cookie.split('; ').map(value => { const at = value.indexOf('='); return { name: value.slice(0, at), value: value.slice(at + 1), url: f.origin }; }));
  const page = await context.newPage(), errors = []; page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message));
  await mkdir('.cache', { recursive: true });
  t.after(async () => { try { if (!t.passed && !page.isClosed()) { await page.screenshot({ path: '.cache/git-feedback-batch-failure.png' }); t.diagnostic((await page.locator('body').innerText()).slice(-5500)); t.diagnostic(JSON.stringify(errors)); } } finally { await browser.close(); } });
  await page.goto(f.origin); await page.getByRole('button', { name: /^(Continue|继续)$/ }).click();
  await page.getByText('Codex batch feedback', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Codex 预设设置', exact: true }).click();
  const review = page.getByRole('region', { name: 'Codex Git 审阅' });
  for (const [path, note] of [['alpha.txt', 'Check alpha boundary.'], ['beta.txt', 'Handle beta failure.']]) {
    await review.getByRole('button', { name: path, exact: true }).click();
    await review.locator(`[data-omaa-git-diff="${path}"]`).waitFor();
    await review.getByRole('button', { name: '评论新文件第 2 行', exact: true }).click();
    await review.getByLabel('行级审阅反馈').fill(note);
    await review.getByRole('button', { name: '加入反馈草稿', exact: true }).click();
  }
  const drafts = review.getByRole('region', { name: '待提交反馈草稿' });
  assert.equal(await drafts.locator('.omaa-git-draft').count(), 2);
  await drafts.getByText('Check alpha boundary.', { exact: true }).waitFor();
  await drafts.getByText('Handle beta failure.', { exact: true }).waitFor();
  await drafts.scrollIntoViewIfNeeded(); await page.screenshot({ path: '.cache/codex-feedback-batch.png' });
  const from = f.requests.length;
  await drafts.getByRole('button', { name: '批量发送并继续修改', exact: true }).click();
  await until(() => f.requests.slice(from).some(payload => payload.tools?.length && JSON.stringify(payload.messages).includes('Please address these 2 code review comments together.')));
  const requests = f.requests.slice(from).filter(payload => payload.tools?.length);
  assert.equal(requests.length, 1, 'both comments use one native model request');
  const messages = JSON.stringify(requests[0].messages);
  for (const text of ['alpha.txt', 'beta.txt', 'Check alpha boundary.', 'Handle beta failure.', 'revision', 'unstaged']) assert(messages.includes(text), text);
  await drafts.waitFor({ state: 'detached' });
  await until(async () => !(await f.api(created.sessionId)).value.running);
  const snapshot = await f.snapshot(created.sessionId);
  const batchEvents = snapshot.records.filter(row => row.event?.type === 'user/message' && JSON.stringify(row.event.data).includes('Please address these 2 code review comments together.'));
  assert.equal(batchEvents.length, 1, 'one durable native user message admits the full feedback batch');
  assert.deepEqual(errors, []);
});
