import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { installedHost, textReply, toolReply, until } from './fixtures/installed-host.mjs';
const execute = promisify(execFile);

test('packed Codex Git review stages real hunks, reverts files and submits line feedback to native session', { timeout: 150000 }, async t => {
  const f = await installedHost(t); await f.install(); await f.boot();
  const git = async (...args) => (await execute('git', args, { cwd: f.workspace, encoding: 'utf8' })).stdout;
  await git('init'); await git('config', 'user.email', 'fixture@example.invalid'); await git('config', 'user.name', 'OMAA fixture');
  const before = Array.from({ length: 24 }, (_, i) => `line ${i + 1}`).join('\n') + '\n';
  const after = before.replace('line 2\n', 'line TWO\n').replace('line 20\n', 'line TWENTY\n');
  await writeFile(join(f.workspace, 'review.txt'), before); await git('add', 'review.txt'); await git('commit', '-m', 'Baseline');
  const baseline = (await git('rev-parse', 'HEAD')).trim();
  const workspace = await f.rpc('workspace/create', { path: f.workspace });
  const created = await f.rpc('session/create', { workspaceId: workspace.workspace.workspaceId, agentPreset: 'omaa-codex' });
  let step = 0;
  f.replyWith(payload => !payload.tools?.length ? textReply('Title') : step++ === 0 ? toolReply('read', { file_path: 'review.txt' }) : step === 2
    ? toolReply('write', { file_path: 'review.txt', content: after }) : textReply('Two distant hunks changed.'));
  await f.prompt(created.sessionId, 'Edit two distant lines'); f.replyWith();
  await f.rpc('session/rename', { sessionId: created.sessionId, title: 'Codex Git scopes' });
  const browser = await chromium.launch({ headless: true, args: ['--use-mock-keychain', '--password-store=basic'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies(f.cookie.split('; ').map(value => { const at = value.indexOf('='); return { name: value.slice(0, at), value: value.slice(at + 1), url: f.origin }; }));
  const page = await context.newPage(), errors = []; page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message));
  await mkdir('.cache', { recursive: true });
  t.after(async () => { try { if (!t.passed && !page.isClosed()) { await page.screenshot({ path: '.cache/git-review-browser-failure.png' }); t.diagnostic((await page.locator('body').innerText()).slice(-6500)); t.diagnostic(JSON.stringify(errors)); } } finally { await browser.close(); } });
  await page.goto(f.origin); await page.getByRole('button', { name: /^(Continue|继续)$/ }).click();
  await page.getByText('Codex Git scopes', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Codex 预设设置', exact: true }).click();
  const review = page.getByRole('region', { name: 'Codex Git 审阅' }), scope = review.getByLabel('Git 比较范围');
  const choose = () => review.getByRole('button', { name: 'review.txt', exact: true }).click();
  await choose(); await review.locator('.omaa-git-hunk').nth(1).waitFor();
  await review.locator('.omaa-git-hunk').first().getByRole('button', { name: '暂存此块', exact: true }).click();
  await until(async () => (await git('diff', '--cached', '--numstat')).trim() === '1\t1\treview.txt');
  assert((await git('diff', '--cached')).includes('line TWO')); assert(!(await git('diff', '--cached')).includes('line TWENTY'));
  await scope.selectOption('staged'); await choose();
  await review.getByRole('button', { name: '取消暂存', exact: true }).click();
  await until(async () => !(await git('diff', '--cached')).trim());
  await scope.selectOption('unstaged');
  await review.getByRole('button', { name: '暂存', exact: true }).click();
  await until(async () => (await git('diff', '--cached', '--numstat')).trim() === '2\t2\treview.txt');
  await scope.selectOption('staged');
  await review.getByRole('button', { name: '取消暂存', exact: true }).click();
  await until(async () => !(await git('diff', '--cached')).trim());
  await scope.selectOption('commit'); await review.getByLabel('比较提交').fill(baseline); await review.getByRole('button', { name: '加载比较', exact: true }).click();
  await choose(); assert.equal(await review.getByRole('button', { name: /暂存|撤回改动/ }).count(), 0);
  await scope.selectOption('branch'); await review.getByLabel('比较基准分支').fill(baseline);
  const branchRead = page.waitForResponse(response => response.url().includes('/omaa/api/git-review?') && new URL(response.url()).searchParams.get('ref') === baseline);
  await review.getByRole('button', { name: '加载比较', exact: true }).click();
  assert.equal((await branchRead).status(), 200);
  assert.equal(await review.getByRole('button', { name: /暂存|撤回改动/ }).count(), 0);
  await scope.selectOption('last-turn');
  await page.locator('[data-changes-review]:visible [data-diff-line]').first().waitFor();
  await page.getByRole('button', { name: 'Codex 预设设置', exact: true }).click();
  await scope.selectOption('unstaged'); await choose();
  await review.locator('.omaa-git-hunk').nth(1).waitFor();
  await review.locator('.omaa-git-hunk').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.cache/codex-git-review.png' });
  const from = f.requests.length;
  await review.getByRole('button', { name: '评论新文件第 2 行', exact: true }).click();
  await review.getByLabel('行级审阅反馈').fill('Keep this line concise.');
  await review.getByLabel('行级审阅反馈').scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.cache/codex-line-feedback.png' });
  await review.getByRole('button', { name: '发送反馈并继续修改', exact: true }).click();
  await until(() => f.requests.slice(from).some(payload => payload.tools?.length && JSON.stringify(payload.messages).includes('Keep this line concise.')));
  const message = JSON.stringify(f.requests.slice(from).find(payload => payload.tools?.length).messages);
  assert(message.includes('unstaged')); assert(message.includes('revision')); assert(message.includes('review.txt')); assert(message.includes('new'));
  await until(async () => !(await f.api(created.sessionId)).value.running);
  await review.getByRole('button', { name: '刷新', exact: true }).click();
  await choose();
  await review.locator('.omaa-git-hunk').nth(1).getByRole('button', { name: '撤回改动此块', exact: true }).click();
  await until(async () => (await readFile(join(f.workspace, 'review.txt'), 'utf8')) === before.replace('line 2\n', 'line TWO\n'));
  await review.getByRole('button', { name: '撤回改动', exact: true }).click();
  await until(async () => (await readFile(join(f.workspace, 'review.txt'), 'utf8')) === before);
  await until(async () => review.getByRole('button', { name: '刷新', exact: true }).isEnabled());
  assert.equal((await git('diff')).trim(), ''); assert.equal((await git('diff', '--cached')).trim(), '');
  await page.screenshot({ path: '.cache/codex-git-reverted.png' });
  assert.deepEqual(errors, []);
});
