import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { installedHost, textReply, toolReply } from './fixtures/installed-host.mjs';

const run = promisify(execFile);
const omaa = fileURLToPath(new URL('../', import.meta.url));
const omd = '/Users/mac/Projects/trisoul_x';
const names = payload => new Set(payload.tools?.map(tool => tool.function.name));
const system = payload => payload.messages.filter(message => message.role === 'system').map(message => typeof message.content === 'string' ? message.content : message.content.map(part => part.text ?? '').join('\n')).join('\n');

test('packed OMD and OMAA coexist with opt-in tools and one native conversation engine', { timeout: 300000 }, async t => {
  const f = await installedHost(t);
  const packed = JSON.parse((await run('npm', ['pack', '--json', '--ignore-scripts', '--pack-destination', f.root], { cwd: omd, timeout: 120000, maxBuffer: 16 * 1024 * 1024 })).stdout)[0];
  const plugin = args => run(process.execPath, [join(omaa, 'node_modules/@deepseek-ai/dsh/lib/bin.js'), 'plugin', '--profile', 'omaa-fixture', ...args], { cwd: omaa, env: { ...process.env, DSH_HOME: f.home }, timeout: 120000, maxBuffer: 16 * 1024 * 1024 });
  await plugin(['add', 'file:' + join(f.root, packed.filename)]);
  await f.boot();
  const baseline = await f.create('standard'); await f.prompt(baseline.sessionId, 'OMD_ONLY_STANDARD');
  const stockBefore = f.requests.findLast(request => request.tools?.length);
  await f.stop();
  await f.install(); await f.boot();
  const created = await f.create('omaa-codex'), id = created.sessionId;
  const initial = await f.api(id); assert.equal(initial.status, 200, JSON.stringify(initial));
  assert.equal(initial.value.omdAvailable, true); assert.equal(initial.value.enhancementActive, false);
  const from = f.requests.length; await f.prompt(id, 'COEXIST_DEFAULT_OFF');
  const ordinary = f.requests.slice(from).find(request => request.tools?.length); assert(ordinary);
  assert(!names(ordinary).has('computer_use')); assert(!names(ordinary).has('codegraph_index'));
  assert(!system(ordinary).includes('CodeGraph is bundled'));
  assert(!system(ordinary).includes('TODO_NUDGE'));
  const enabled = await f.api(id, { enhancement: true }); assert.equal(enabled.status, 200, JSON.stringify(enabled)); assert.equal(enabled.value.enhancementActive, true);
  const onFrom = f.requests.length; await f.prompt(id, 'COEXIST_ENABLED');
  const on = f.requests.slice(onFrom).find(request => request.tools?.length); assert(on);
  for (const name of ['computer_use', 'computer_use_reset', 'codegraph_index']) assert(names(on).has(name), name + ' absent with OMD enhancement');
  assert(JSON.stringify(on.messages).includes('CodeGraph is bundled'), 'enabled tool guide must reach the actual provider');
  await writeFile(join(f.workspace, 'example.mjs'), 'export function sum(a,b) { return a+b; }\n');
  let step = 0;
  f.replyWith(payload => payload.tools?.length && step++ === 0 ? toolReply('codegraph_index', {}) : textReply('CodeGraph execution completed'));
  const indexed = await f.prompt(id, 'COEXIST_NATIVE_CODEGRAPH');
  const indexResult = indexed.records.findLast(row => row.event?.type === 'tool/result')?.event.data;
  assert(indexResult && !indexResult.message.isError, 'real bundled CodeGraph index failed: ' + JSON.stringify(indexResult));
  f.replyWith();
  const disabled = await f.api(id, { enhancement: false }); assert.equal(disabled.status, 200); assert.equal(disabled.value.enhancementActive, false);
  step = 0;
  f.replyWith(payload => payload.tools?.length && step++ === 0 ? toolReply('computer_use', { command: 'snapshot' }) : textReply('Disabled guard verified'));
  const rejected = await f.prompt(id, 'COEXIST_DISABLED_GUARD');
  assert.match(JSON.stringify(rejected.records), /OMD enhancement is disabled/);
  f.replyWith();
  const stock = await f.create('standard'); await f.prompt(stock.sessionId, 'COEXIST_STANDARD');
  const stockRequest = f.requests.findLast(request => request.tools?.length);
  assert(!system(stockRequest).includes('You are Codex'));
  assert.deepEqual([...names(stockRequest)].sort(), [...names(stockBefore)].sort(), 'OMAA installation must preserve the existing OMD standard tools');
  const headings = payload => system(payload).split('\n').filter(line => /^#{1,3} |^<[\w:-]+>/.test(line));
  assert.deepEqual(headings(stockRequest), headings(stockBefore), 'existing OMD standard sections must be preserved');
  await f.stop(); await f.boot();
  const cold = await f.api(id); assert.equal(cold.status, 200); assert.equal(cold.value.enhancement, false);
  await f.stop(); await f.uninstall(); await plugin(['remove', 'trisoul_x']);
  await f.install(); await plugin(['add', 'file:' + join(f.root, packed.filename)]); await f.boot();
  const reverse = await f.create('omaa-grok');
  assert.equal((await f.api(reverse.sessionId)).value.enhancementActive, false);
  assert.equal((await f.api(reverse.sessionId, { enhancement: true })).value.enhancementActive, true);
  const reverseFrom = f.requests.length; await f.prompt(reverse.sessionId, 'OMAA_BEFORE_OMD');
  const reverseRequest = f.requests.slice(reverseFrom).find(request => request.tools?.length);
  assert(names(reverseRequest).has('computer_use')); assert(names(reverseRequest).has('codegraph_index'));
  assert(JSON.stringify(reverseRequest.messages).includes('CodeGraph is bundled'), 'reverse installation order must also register the initial tool guide');
});
