import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';
import { installedHost, textReply } from './fixtures/installed-host.mjs';

test('packed Pi forks its first completed turn and opens the native child with source in the branch tree', { timeout: 120000 }, async t => {
  const f = await installedHost(t); await f.install(); await f.boot();
  const workspace = await f.rpc('workspace/create', { path: f.workspace });
  const source = await f.rpc('session/create', { workspaceId: workspace.workspace.workspaceId, agentPreset: 'omaa-pi' });
  f.replyWith(payload => textReply(payload.tools?.length ? 'Pi native turn completed.' : 'Pi title'));
  await f.prompt(source.sessionId, 'PI FIRST COMPLETE');
  await f.prompt(source.sessionId, 'PI SECOND COMPLETE');
  await f.rpc('session/rename', { sessionId: source.sessionId, title: 'Pi source branch' });
  const api = async id => {
    const response = await fetch(f.origin + '/omaa/api/pi-branches?session=' + encodeURIComponent(id), { headers: { cookie: f.cookie } });
    assert.equal(response.status, 200); return response.json();
  };
  const original = await api(source.sessionId);
  assert.equal(original.points.length, 2);
  const browser = await chromium.launch({ headless: true, args: ['--use-mock-keychain', '--password-store=basic'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies(f.cookie.split('; ').map(value => { const at = value.indexOf('='); return { name: value.slice(0, at), value: value.slice(at + 1), url: f.origin }; }));
  const page = await context.newPage(), errors = []; page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message));
  await mkdir('.cache', { recursive: true });
  t.after(async () => { try { if (!t.passed && !page.isClosed()) { await page.screenshot({ path: '.cache/pi-branches-browser-failure.png' }); t.diagnostic((await page.locator('body').innerText()).slice(-4500)); t.diagnostic(JSON.stringify(errors)); } } finally { await browser.close(); } });
  await page.goto(f.origin); await page.getByRole('button', { name: /^(Continue|继续)$/ }).click();
  await page.getByText('Pi source branch', { exact: true }).first().click();
  await page.getByRole('button', { name: 'Pi Coding Agent 预设设置', exact: true }).click();
  const panel = page.getByRole('region', { name: 'Pi 分支导航' });
  const position = panel.getByLabel('Pi 分叉位置');
  await position.selectOption(String(original.points[0].seq));
  assert.equal(await panel.getByLabel('分叉时附带离开分支摘要').isChecked(), false);
  const from = f.requests.length;
  const forked = page.waitForResponse(response => new URL(response.url()).pathname === '/omaa/api/pi-branches' && response.request().method() === 'POST');
  await panel.getByRole('button', { name: '创建并打开新分支', exact: true }).click();
  const response = await forked; assert.equal(response.status(), 200);
  const child = await response.json();
  assert.notEqual(child.sessionId, source.sessionId); assert.equal(child.parentSessionId, source.sessionId); assert.equal(child.summaryIncluded, false);
  await page.waitForFunction(() => !document.body.innerText.includes('PI SECOND COMPLETE'));
  await page.getByText('PI FIRST COMPLETE', { exact: true }).last().waitFor();
  await page.getByRole('button', { name: 'Pi Coding Agent 预设设置', exact: true }).click();
  await panel.getByRole('list', { name: '已有分支' }).getByRole('button', { name: /当前/ }).waitFor();
  await panel.getByText('每条分支是一个原生 DSH 会话，共享工作目录；切换分支不会还原文件。', { exact: true }).waitFor();
  const tree = await api(child.sessionId);
  assert(tree.branches.some(branch => branch.sessionId === source.sessionId));
  assert(tree.branches.some(branch => branch.sessionId === child.sessionId && branch.current));
  assert.equal(tree.branches.find(branch => branch.sessionId === child.sessionId).cwd, tree.branches.find(branch => branch.sessionId === source.sessionId).cwd);
  assert.equal((await api(source.sessionId)).points.length, 2, 'source history remains intact');
  assert.equal(tree.points.length, 1, 'child inherits only the chosen completed prefix');
  assert.equal(f.requests.length, from, 'default fork and navigation make no summary/model request');
  await panel.scrollIntoViewIfNeeded(); await page.screenshot({ path: '.cache/pi-native-branches.png' });
  const sourceButton = panel.getByRole('button', { name: /Pi source branch/ }).filter({ hasNotText: '当前' });
  await sourceButton.click(); await page.getByText('PI SECOND COMPLETE', { exact: true }).waitFor();
  assert.deepEqual(errors, []);
});
